### ISSUE TITLE
question. Mobile broadband connection support.

### ISSUE THREAD

**Issue by MorphicResonance** [kotoko/voidlinux-iso-extra#1]
I want to make sure your iso is mobile broadband connection friendly.
Is your ISO supports mobile broadband connection out of the box? I know the official iso [had problems with this](https://www.reddit.com/r/voidlinux/comments/ekzll3/trap_of_the_void_mobile_broadband_connection/) some time ago

**Comment by kotoko** [comment]
The only difference from official ISO (at the moment) is that it has additional programs installed. Programs/packages are defined here:
https://github.com/kotoko/voidlinux-iso-extra/blob/beb6c5a35f6dc75e480307f557056646f33e5898/gen.sh#L3-L4

I'm skeptical about adding packages from linked thread because I use this ISO primarily for myself and I don't even have 3G modem.

At the same time I encourage you to experiment yourself. Recently I added workflow for Github Actions so this should be super easy:
1. Fork this repository.
2. Enable Github Actions in github settings for forked repository.
3. Append `usb-modeswitch ModemManager mobile-broadband-provider-info` to `PKGS` in `gen.sh` and push commit to github.
4. Wait for build to complete.
5. Download artifact (ISO file) from github.
(You could even change workflow file to automatically run build process every month or something like that.)

**Comment by MorphicResonance** [comment]
Tried to install your iso. It seems like it only support mbr disk . Failed to create gpt loader flash through rufus and failed to install on gpt disk.  it comes without proper efi folder. However I've created gpt boot flash and installed from official xfce-iso on gpt. Of course, it comes without 'visible' support of  [gobi300 modem ](https://helperbyte.com/questions/107462/thinkpad-x230-not-working-3g-modem-gobi-3000). Maybe additional packages will help. I know that debian distro support 3g modem right from the  live cd.
Please add gpt version of iso.

**Comment by kotoko** [comment]
Use [Ventoy](https://www.ventoy.net/en/index.html).

**Comment by MorphicResonance** [comment]
I've used ventoy (good one), and tried to install your iso several times but without success.  It was ended with the same error like this : running grub-install  /dev/sda .. chroot: failded to run command grub-install .. no such file  or directory. 

I've used the same settings as with installation from other official  isos(glib) with xfce and mate and unofficial from voidbuilds.xyz such as with i3 / kde. They were installed well. The other thing that mobile broadband connection isn't working with them with my dusty sierra wireless mc 8355 gobi 3000 modem without 'magic tricks' . 

The problem in this iso or it does require special preparation before installing. The lack of initial information is also a problem.

**Comment by kotoko** [comment]
`error like this : running grub-install /dev/sda .. chroot: failded to run command grub-install .. no such file or directory.`
It probably means that you do not have installed grub (program) in your system or device `/dev/sda` does not exist. It is not clear to me when this command is executed? During installation from livecd? During copying ISO to USB?

10 months ago I successfully installed void in EFI mode on real laptop using ventoy and have zero problems. (Copy ISO to USB. Use ventoy to boot. Use void-installer. Done.)

Assuming this error was shown during installation from livecd one of two situations could happen:
* grub package is not installed (I doubt that but it is possible),
* during configuration you choose to install system on `/dev/sda` which does not exist (this is my guess).

Anyway I'll leave this bug open. When I'll have free time I'll try to install it in VirtualBox and see what happens.

**Comment by MorphicResonance** [comment]
Error message is executed during the actual installation from iso, after copiyng system files before final reboot. I have no problem to make bootable flash with ventoy and installed several times on efi system with gpt from official iso and even from unofficial. All installs were with graphical environment and not the basic. Right now I'm trying to load modem drivers into void linux with xcfe. The problem that all of these ISOs without usbmodem switch and modemmanager but basic ISO failed to install.
Test it and maybe I'll get full-fledged os .

**Comment by kotoko** [comment]
According to readme from `void-mklive` developers use that project to generate ISOs. I'm using the same project so the only difference should be only in passed parameters/configuration. The most obvious one is the parameter that adds additional packages.

Generally graphical programs do not affect in any way other installed programs. If you installed linux using xfce you should be able to install linux using "base image" without graphical environment and vice versa.

I generated ISO using GA and booted in VirtualBox. It actually does not have `grub` package installed. You can add `grub` to `PKGS` as a workaround. It looks like it is bug inside `void-mklive`: https://github.com/void-linux/void-mklive/issues/223 .

**Comment by kotoko** [comment]
It turns out that there is [short list of packages](https://github.com/void-linux/void-mklive/blob/488d58ff2d55e930cfa6626e181dda4c0004b052/build-x86-images.sh.in#L29-L31) (including grub) that must be explicitly added to generate working ISO. I added missing packages to `gen.sh`.

@MorphicResonance Please try again now.

**Comment by MorphicResonance** [comment]
Tried basic install based on your iso. Installed successfully when added grub-x86_64-efi package to iso. Looks like this package was away. 
Anyway if you need to install stable as efi and your computer proposes to install in legacy boot mode into startup menu, toggle it to [UEFi only] and CSM support [No].
